	<h3 class="hidden">The Armstrong Collection Artifacts 3-D Gallery</h3>

	<div id="collection-3d-gallery" class="section">

	  <script type="text/javascript" src="3d-objects/object2vr_player.js"></script>
	  <script type="text/javascript" src="3d-objects/skin-small.js"></script>

	  <div class="collection-3d-gallery-row">

	  <!--mask 3d object-->
	  <h4 class="hidden">Flight Mask</h4>

	  <div class="collection-3d-object">

		  <div id="container-mask" class="container-individual-object-horizontal">
		  This content requires HTML5 &amp; Javascript or Adobe Flash Player Version 9 or higher.
		  </div>

		  <script type="text/javascript">
			  // create the object player with the container
			  obj=new object2vrPlayer("container-mask");
			  // add the skin object
			  skin=new object2vrSkin(obj);
			  // load the configuration
			  obj.readConfigUrl("3d-objects/flight-mask/small/jpeg_derivatives_out.xml");
			  // hide the URL bar on the iPhone
			  hideUrlBar();
		  </script>
		  <noscript>
			  <p><b>Please enable Javascript!</b></p>
		  </noscript>

		  <p class="collection-3d-object-description">Flight Mask<br />
		  <a class="link-icon" href="armstrong-flight-mask.html">View a larger rotatable image of this object...</a></p>


	  </div>
	  <!--end mask 3d object-->


	  <!--gemini heat shield 3d object-->
	  <h4 class="hidden">Encapsulated Mounted Heat Shield of Gemini VIII, First Docking in Space,March 16, 1966</h4>

	  <div class="collection-3d-object">

		  <div id="container-gemini-heat-shield" class="container-individual-object-horizontal">
			  This content requires HTML5 &amp; Javascript or Adobe Flash Player Version 9 or higher.
		  </div>

		  <script type="text/javascript">
			  // create the object player with the container
			  obj=new object2vrPlayer("container-gemini-heat-shield");
			  // add the skin object
			  skin=new object2vrSkin(obj);
			  // load the configuration
			  obj.readConfigUrl("3d-objects/gemini_heat_shield/small/gemini_select_images_out.xml");
			  // hide the URL bar on the iPhone
			  hideUrlBar();
		  </script>
		  <noscript>
			  <p><b>Please enable Javascript!</b></p>
		  </noscript>

		  <p class="collection-3d-object-description">Encapsulated Mounted Heat Shield of Gemini VIII, First Docking in Space,<br />March 16, 1966<br />
		  <a class="link-icon" href="armstrong-gemini-heat-shield.html">View a larger rotatable image of this object...</a></p>

	  </div>
	  <!--end heat shield 3d object-->

	  <!--artificial hip 3d object-->
	   <h4 class="hidden">Artificial Hip developed by Armstrong<!-- and the HARP Research Group--></h4>

	  <div class="collection-3d-object">

		  <div id="container-artificial-hip" class="container-individual-object-horizontal">
		  This content requires HTML5 &amp; Javascript or Adobe Flash Player Version 9 or higher.
		  </div>


		  <script type="text/javascript">
			  // create the object player with the container
			  obj=new object2vrPlayer("container-artificial-hip");
			  // add the skin object
			  skin=new object2vrSkin(obj);
			  // load the configuration
			  obj.readConfigUrl("3d-objects/artificial_hip/small/jpeg_out.xml");
			  // hide the URL bar on the iPhone
			  hideUrlBar();
		  </script>
		  <noscript>
			  <p><b>Please enable Javascript!</b></p>
		  </noscript>

		  <p class="collection-3d-object-description">Artificial Hip developed by Armstrong<!-- and the HARP Research Group--><br />
		  <a class="link-icon" href="armstrong-artificial-hip.html">View a larger rotatable image of this object...</a></p>

	  </div>
	  <!--end artificial hip 3d object-->
	  </div>

	  <!--begin 2nd row-->
	  <div class="collection-3d-gallery-row">

	  <!--freedom of flight award-->
	   <h4 class="hidden">&ldquo;Freedom of Flight&rdquo; Award, August 1, 1988</h4>

	  <div class="collection-3d-object vertical-object">

		  <div id="container-freedom-of-flight-award" class="container-individual-object-vertical">
		  This content requires HTML5 &amp; Javascript or Adobe Flash Player Version 9 or higher.
		  </div>

		  <script type="text/javascript">
			  // create the object player with the container
			  obj=new object2vrPlayer("container-freedom-of-flight-award");
			  // add the skin object
			  skin=new object2vrSkin(obj);
			  // load the configuration
			  obj.readConfigUrl("3d-objects/freedom_of_flight/small/jpeg_out.xml");
			  // hide the URL bar on the iPhone
			  hideUrlBar();
		  </script>
		  <noscript>
			  <p><b>Please enable Javascript!</b></p>
		  </noscript>

	  <p class="collection-3d-object-description">&ldquo;Freedom of Flight&rdquo; Award, August 1, 1988<br />
		  <a class="link-icon" href="armstrong-flight-award.html">View a larger rotatable image of this object...</a></p>

	  </div>

	  <!--end freedom of flight award-->

	  <!--metal disc 3d object-->
	   <h4 class="hidden">Ballistic Particle Test, Metal Disc</h4>

	  <div class="collection-3d-object vertical-object">

		  <div id="container-metal-disc" class="container-individual-object-horizontal">
		  This content requires HTML5 &amp; Javascript or Adobe Flash Player Version 9 or higher.
		  </div>

		  <script type="text/javascript">
			  // create the object player with the container
			  obj=new object2vrPlayer("container-metal-disc");
			  // add the skin object
			  skin=new object2vrSkin(obj);
			  // load the configuration
			  obj.readConfigUrl("3d-objects/metal_disc/normal_background/small/normal_background_out.xml");
			  // hide the URL bar on the iPhone
			  hideUrlBar();

		  </script>
		  <noscript>
			  <p><b>Please enable Javascript!</b></p>
		  </noscript>

		  <p class="collection-3d-object-description">Ballistic Particle Test,<br />Metal Disc<br />
		  <a class="link-icon" href="armstrong-metal-disc.html">View a larger rotatable image of this object...</a></p>

	  </div>

	  <!--end metal disc 3d object-->

	  <!--chamber of commerce 3d object-->
	   <h4 class="hidden">Cincinnati Chamber of Commmerce Award, January 31, 1986</h4>

	  <div class="collection-3d-object vertical-object">

		  <div id="container-chamber-of-commerce-award" class="container-individual-object-vertical">
		  This content requires HTML5 &amp; Javascript or Adobe Flash Player Version 9 or higher.
		  </div>

		  <script type="text/javascript">
			  // create the object player with the container
			  obj=new object2vrPlayer("container-chamber-of-commerce-award");
			  // add the skin object
			  skin=new object2vrSkin(obj);
			  // load the configuration
			  obj.readConfigUrl("3d-objects/chamber_of_commerce/small/3d_jpeg_out.xml");
			  // hide the URL bar on the iPhone
			  hideUrlBar();
		  </script>
		  <noscript>
			  <p><b>Please enable Javascript!</b></p>
		  </noscript>

		  <p class="collection-3d-object-description">Cincinnati Chamber of Commmerce Award,<br />January 31, 1986<br />
		  <a class="link-icon" href="armstrong-chamber-award.html">View a larger rotatable image of this object...</a></p>

	  </div>

	  <!--end chamber of commerce 3d object-->

	  </div><!--end collection-3d-objects-gallery-->

	<!--gallery textual instructions-->
	<div id="collection-3d-gallery-text">
		  <p class="top-p">Rotate, enlarge and explore these objects in the UC Neil Armstrong Commemorative Archives Collection.</p>
		  <!--<p><a class="link-icon" href="collection-3d-objects.html" >View even larger rotatable images...</a></p>-->
	</div><!--end collection-3d-gallery-text-->
	<!--end gallery textual instructions-->

	</div>
