    <!--begin learn more page-->
        
    <div id="learn-more">
  
<h2 class="center">Learn More</h2>    
    
    <div class="learn-more-section">
    	
        <h3 class="essay-title">NEIL ARMSTRONG HIMSELF REPLIES:</h3>
    
    		<ul>
				<li><a class="link-icon" href="http://www.npr.org/blogs/krulwich/2010/12/08/131910930/neil-armstrong-talks-about-the-first-moon-walk" >&ldquo;Neil Armstrong Talks About The First Moon Walk&rdquo; by Robert Krulich on &lsquo;Krulich Wonders&rsquo; on NPR</a></li>
    		</ul>
   	</div>
    
    <div class="learn-more-section">
    
    	<h3 class="essay-title">MORE UC FEATURES:</h3>
    	
        	<ul>
                <li><a class="link-icon" href="http://libapps.libraries.uc.edu/liblog/2012/09/11/dr-h-j-heimlich-project-working-with-neil-armstrong/" >The Dr. H. J. Heimlich Project Blog at UC Libraries: &ldquo;Working with Neil Armstrong&rdquo;</a></li>
        
                <li><a class="link-icon" href="http://ceas.uc.edu/about/neil-armstrong-remembered.html" >UC College of Engineering and Applied Science: Neil Armstrong Remembered</a></li>    
            </ul>
            
            
    </div>
    
    <div class="learn-more-section">
    
    	<h3 class="essay-title">NASA FEATURES:</h3>
    
    		<ul>
                <li><a class="link-icon" href="http://www.nasa.gov/vision/space/features/SETP_NeilArmstrongLunarLander.html" >Neil Armstrong Shows How to Land on the Moon</a></li>
                
                <li><a class="link-icon" href="http://www.nasa.gov/topics/people/galleries/armstrong.html#.UmWpRpRASGo" >NASA Image Gallery: Neil Armstrong, 1930-1912</a></li>
                
                <li><a class="link-icon" href="http://www.nasa.gov/centers/glenn/about/bios/neilabio.html" >The NASA Biography of Neil Armstrong from the NASA's Glenn Research Center</a></li>
                
                <li><a class="link-icon" href="http://www.jsc.nasa.gov/history/oral_histories/ArmstrongNA/ArmstrongNA_9-19-01.pdf" >NASA Johnson Space Center Oral History Project: Oral History Transcript: Neil Armstrong Interviewed by Dr. Stephen E. Ambrose and Dr. Douglas Brinkley, September 2001</a></li>
    		</ul>
    </div>
    
    <div class="learn-more-section">
    
    	<h3 class="essay-title">APOLLO 11:</h3>
        
        	<ul>
				<li><iframe class="learn-more-iframe" id="iframe-google-earth" width="560" height="315" src="https://www.youtube.com/embed/zHJ77RsnFXI?rel=0" frameborder="0" allowfullscreen></iframe></li>
    			<li><a class="link-icon" href="http://www.google.com/earth/explore/showcase/moon.html" >MOON in Google Earth. Take tours of landing sites, narrated by Apollo astronauts, view 3D models of landed spacecraft, zoom into 360-degree photos to see astronauts' footprints and watch rare TV footage of the Apollo missions</a></li>
    
                <li><a class="link-icon" href="http://blog.nasm.si.edu/highlights-from-the-collection/neil-armstrongs-apollo-11-extravehicular-gloves-and-visor/" >&ldquo;Neil Armstrong's Apollo 11 Extravehicular Gloves and Visor&rdquo; posted on September 6, 2012 by The Smithsonian National Air and Space Museum</a></li>
                  
               	<li><a class="link-icon" href="http://www.ohiomemory.org/cdm/compoundobject/collection/p267401coll36/id/24860/rec/2" >An Image of the Wright Flyer Fabric Taken to the Moon by Neil Armstrong at the Ohio Historical Society Website Digital Collection</a></li>
                  
               	<li><a class="link-icon" href="http://www.hq.nasa.gov/alsj/a11/a11.landing.html" >NASA Apollo 11 Lunar Surface Journal: The First Lunar Landing (Transcripts and Audio Clips)</a></li>
                  
               	<li><a class="link-icon" href="http://www.nasa.gov/mission_pages/apollo/40th/apollo_graham_09.html" >Apollo 40th Anniversary: &ldquo;Hiring a National Hero&rdquo; from the NASA's Glenn Research Center</a></li>
                  
              	<li><a class="link-icon" href="http://life.time.com/history/apollo-11-to-the-moon-and-back-life-covers-the-1969-lunar-landing/#1" >LIFE Magazine: &lsquo;To the Moon and Back&rsquo;: LIFE Covers the Apollo 11 Mission</a></li>
                  
             	<li><a class="link-icon" href="http://en.wikipedia.org/wiki/Apollo_11" >Apollo 11 page at Wikipedia</a></li>
    		</ul>
    </div>
   
   
    <div class="learn-more-section">

        <h3 class="essay-title">HONORING HIS LIFE:</h3>
			
            <ul>
   			
    			<li><a class="link-icon" href="http://www.whitehouse.gov/the-press-office/2012/08/27/presidential-proclamation-death-neil-armstrong" >Presidential Proclamation &mdash;Death of Neil Armstrong, August 27, 2012</a></li>
    
    			<li><a class="link-icon" href="http://www.today.com/id/48861170/ns/today-today_tech/t/lunar-pioneers-vips-honor-astronaut-neil-armstrong/#.UmWplZRASGp" >&ldquo;Lunar pioneers and VIPs honor astronaut Neil Armstrong&rdquo;from NBC News</a></li>
    
    			<li><a class="link-icon" href="http://www.nytimes.com/2012/08/26/science/space/neil-armstrong-dies-first-man-on-moon.html?pagewanted=all&amp;_r=2&" >&ldquo;Neil Armstrong, First Man on the Moon, Dies at 82&rdquo; from the New York Times, by John Noble Wilford</a></li>
    
    			<li><a class="link-icon" href="http://blog.nasm.si.edu/history/remembering-neil-armstrong/" >&ldquo;Remembering Neil Armstrong&rdquo; posted on August 25, 2012 by The Smithsonian National Air and Space Museum</a></li>
    
    			<li><a class="link-icon" href="http://www.airspacemag.com/multimedia/Neil-Armstrong-In-His-Own-Words-167547355.html?c=y&amp;page=1&amp;navigation=thumb#IMAGES" >&ldquo;Neil Armstrong, In His Own Words&rdquo; from the Smithsonian Air and Space Museum, by Tony Riechhardt</a></li>
    		</ul>
   	</div>
     
    <div class="learn-more-section">

        <h3 class="essay-title">NEWSPAPER FEATURES:</h3>
    		<ul>
            
    			<li><a class="link-icon" href="http://www.enquirer.com/editions/1999/07/18/loc_neil_armstrong_the.html" >&ldquo;The Moon Landing: 30 Years Later&rdquo; &mdash;Neil Armstrong, the Reluctant Hero from the Cincinnati Enquirer, July 18, 1999 by John Johnston, Saundra Amrhein, Richelle Thompson</a></li>
    		</ul>
    </div>
    
    
    <div class="learn-more-section">

        <h3 class="essay-title">HIS TIME AT PURDUE:</h3>
    
    		<ul>
    		
            	<li><a class="link-icon" href="http://www.purdue.edu/armstrong/" >&ldquo;Purdue remembers Neil Armstrong&rdquo; &mdash;Purdue University</a></li>
    
    			<li><a class="link-icon"  href="http://www.kkpsi.org/on-the-passing-of-neil-armstrong/" >&ldquo;On the Passing of Neil Armstrong&rdquo; from the Kappa Kappa Psi National Honorary Band Fraternity, of which Neil Armstrong was made an honorary member at Purdue University in 1966.</a></li>
				<li><a class="link-icon"  href="http://collections.lib.purdue.edu/flight-and-space/other" >Explore the Neil A. Armstrong Papers Collection in the Purdue University Libraries Barron Hilton Flight and Space Exploration Archives</a></li>
    
    		</ul>
    </div>
    
    
    <div class="learn-more-section">
    
    	<h3 class="essay-title">BOOKS AND DOCUMENTARIES:</h3>
        
        	<ul>
				<li><iframe class="learn-more-iframe" id="iframe-nova" width="512" height="376" src="http://video.pbs.org/viralplayer/2365380076" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" seamless></iframe></li>
            
            	<li>First Man, The Life of Neil A. Armstrong: The Essential Biography by James R. Hansen</li>  
                                
                <li>Neil Armstrong: Young Flyer by Montrew Dunham</li>
                
                <li><a class="link-icon" href="http://www.imdb.com/rg/em_share/title_web/title/tt0925248" >&ldquo;In the Shadow of the Moon&rdquo;(2007)
                The surviving crew members from NASA's Apollo missions tell their story in their own words</a></li>

                <li><a class="link-icon" href="http://airandspace.si.edu/research/publications/detail.cfm?id=203" >Spacesuits: The Smithsonian National Air and Space Museum Collection</a></li>
          	</ul>
 	</div>
     
    <div class="learn-more-section">
    
    	<h3 class="essay-title">MUSEUMS:</h3>
    
    		<ul>
				<li><a class="link-icon" href="http://blog.nasm.si.edu/behind-the-scenes/reboot-the-suit/" >Reboot the Suit: the Smithsonian National Air and Space Museum Kickstarter campaign to conserve, digitize and display Neil Armstrong's Apollo 11 spacesuite in time for the 50th anniversary of the Apollo Moon landing.</a></li>
                <li><a class="link-icon"  href="http://www.armstrongmuseum.org/" >Ohio HIstorical Society's Armstrong Air and Space Museum in Wapakoneta, Ohio</a></li>
                
                <li><a class="link-icon"  href="http://www.cincymuseum.org/science/neil-armstrong" >Cincinnati Museum Center: In Memory of Neil Armstrong: August 5, 1930 - August 25, 2012. Including a link to the transcripts of Armstrong's speech upon receiving NASA's Ambassador of Exploration Award at a ceremony held in Cincinnati Museum Center's Reakirt Auditorium on April 18, 2006</a></li>
                
                <li><a class="link-icon"  href="http://www.ohiomemory.org/cdm/compoundobject/collection/p267401coll36/id/24860/rec/2" >An Image of the Wright Flyer Fabric Taken to the Moon by Neil Armstrong at the Ohio Historical Society Website Digital Collection</a></li>
                
                <li><a class="link-icon"  href="http://www.firstflightwarren.org/home.html" >First Flight Lunar Module, A Replica of the Apollo 11 Lunar Landing Module</a></li>
           </ul>
  	</div>
   
   	</div>
    <!--end learn more-->

