<div id="time-at-uc" class="section"> 

	<img src="images/time-at-uc-image.jpg" alt="Armstrong creates a paper airplane at an event hosted by the American Institute of Aeronautics and Astronautics student chapter. Photo of Armstrong by Ralph Spitzen (Eng '74, MBA '76)." />
	
	<div id="time-at-uc-header">
	
			<h2>His Time at UC 1971-79</h2>
	
			<p class="page-subtitle">
					&ldquo;I am, and ever will be, a white-socks, pocket-protector, nerdy engineer. And I take substantial pride in the accomplishments of my profession. Science is about what is; engineering is about what can be.&rdquo;        		
				</p>
			<p class="source">&mdash; Neil Armstrong, February 2000, at National Press Club event including him among the 20th Century's Top 20 Engineering Achievements.</p>
		

					
	</div><!--end time-at-uc-header-->

</div><!--end section time-at-uc-->	
