 <!--timeline gallery-->
<h3 class="hidden">Neil Armstrong Timeline Gallery</h3>

<div id="sequence-theme-timeline" class="section">
	<div id="sequence-timeline">

		<ul class="sequence-canvas">
			<li class="animate-in">
				<h4 class="title">1930</h4>
				<h5 class="subtitle">Born Aug 5, 1930 on his grandparents&rsquo; farm near Wapakoneta, Ohio.</h5>

					<img class="timeline-image-horizontal left top" src="images/1930-wapakoneta-photo.jpg" alt="Downtown Wapakoneta, Ohio, within the bounds of the Wapakoneta Commercial Historic District. Note the Wapa Theater on the left. Photo shot by Derek Jensen" />

						<p class="timeline-image-horizontal left timeline-description-horizontal top-desc">Downtown Wapakoneta, Ohio, within the bounds of the Wapakoneta Commercial Historic District. Note the Wapa Theater on the left. Photo shot by Derek Jensen</p>

					<iframe class="iframe bottom" width="420" height="315" src="http://www.youtube.com/embed/CE2FcSwyxzA?rel=0" title="Neil Armstrong, The Real Right Stuff: 1955&ndash;1962. Video: NASA" allowfullscreen></iframe>
			</li>

			<li>
				<h4 class="title">1936</h4>
				<h5 class="subtitle">His father took him on his first airplane ride in a Ford Tri-Motor airplane in Warren, Ohio.</h5>

					<img class="timeline-image-vertical left top" src="images/1936-armstrong-age-6-photo.jpg" alt="Childhood Photo of Neil Armstrong, age 6" title="Childhood Photo of Neil Armstrong, age 6" />

						<p class="timeline-image-vertical left timeline-description-vertical narrow top-desc-vert">Childhood Photo of Neil Armstrong, age 6.</p>

					<img class="timeline-image-horizontal right-horizontal bottom" src="images/1936-airplane-photo.jpg" alt="An EAA Ford Tri-Motor Airplane." title="Photo of Ford Tri-Motor Airplane" />

						<p class="timeline-image-horizontal right-horizontal timeline-description-horizontal bottom-desc">An EAA Ford Tri-Motor Airplane.</p>
			</li>

			<li>
				<h4 class="title">1939</h4>
				<h5 class="subtitle">He started building model airplanes at age nine.</h5>

					<img class="timeline-image-horizontal left top" src="images/1939-armstrong-with-model-airplane.jpg" alt="Childhood photo of Neil Armstrong with Model Airplane." />

						<p class="timeline-image-horizontal left timeline-description-horizontal top-desc">Childhood photo of Neil Armstrong with Model Airplane.</p>

					<img class="timeline-image-horizontal right-horizontal bottom" src="images/uc-armstrong-1979-at-desk.jpg" alt="Armstrong at his UC desk in 1979, behind a model NASA aircraft. Photo Credit: Peggy Palange, UC Public Information Office" />

						<p class="timeline-image-horizontal right-horizontal timeline-description-horizontal bottom-desc">Armstrong at his UC desk in 1979, behind a model NASA aircraft. Photo Credit: Peggy Palange, UC Public Information Office</p>
			</li>

			<li>
				<h4 class="title">1947</h4>
				<h5 class="subtitle">He earned his student pilot's license in 1946 before he had a driver's license. He graduated from Blume High School in 1947 and enrolled in Purdue University on Navy Scholarship.</h5>

				<img class="timeline-image-horizontal center-horizontal middle" src="images/1947-yearbook-photo.jpg" alt="Neil Armstrong's Senior Picture in the Blume High School Yearbook, 1947." />

						<p class="timeline-image-horizontal center-horizontal timeline-description-horizontal middle-desc">Neil Armstrong's Senior Picture in the Blume High School Yearbook, 1947.</p>
			</li>

			<li>
				<h4 class="title">1950</h4>
				<h5 class="subtitle">He was called to active duty during the Korean War at the age of 19, and became the youngest fully qualified Naval Aviator in his squadron when he was 20.</h5>

					<img class="timeline-image-vertical left top" src="images/armstrong-usnr-uniform.jpg" alt="Neil Armstrong in his US Navy Uniform, 1951, found tucked in his USNR Aviators Flight Log Book. Both in the UC Neil Armstrong Commemorative Archives Collection." />

						<p class="timeline-image-vertical left timeline-description-vertical top-desc-vert">
							<a class="link-icon" href="http://hdl.handle.net/2374.UC/713465">Neil Armstrong in his US Navy Uniform, 1951, found tucked in his USNR Aviators Flight Log Book. Both in the UC Neil Armstrong Commemorative Archives Collection.</a></p>

					<img class="timeline-image-vertical right-vertical bottom" src="images/armstrong-flight-log-book-cover.jpg" alt="Aviators Flight Log Book, Neil Armstrong, USNR, 1949 in the UC Neil Armstrong Commemorative Archives Collection." />

						<p class="timeline-image-vertical right-vertical timeline-description-vertical narrow bottom-desc-vert">
							<a class="link-icon" href="http://hdl.handle.net/2374.UC/713465">Aviators Flight Log Book, Neil Armstrong, USNR, 1949 in the UC Neil Armstrong Commemorative Archives Collection.</a></p>
			</li>

			<li>
				<h4 class="title">1955</h4>
				<h5 class="subtitle">He graduated from Purdue and became a test pilot for the National Advisory Committee for Aeronautics.</h5>

					<img class="timeline-image-horizontal center-horizontal middle" src="images/1955-purdue-statue.jpg" alt="A likeness of Neil Armstrong sits outside Neil Armstrong Hall of Engineering on the campus of Purdue University in West Lafayette, Indiana. Photo Credit: Huw Williams" />

						<p class="timeline-image-horizontal center-horizontal timeline-description-horizontal middle-desc">A likeness of Neil Armstrong sits outside Neil Armstrong Hall of Engineering on the campus of Purdue University in West Lafayette, Indiana. Photo Credit: Huw Williams</p>

			</li>
			<li>
				<h4 class="title">1958</h4>
				<h5 class="subtitle">He test-piloted the X-15, which he set a record flight having reached an altitude of 207,500 feet and a speed of 3,989 miles per hour.</h5>

					<img class="timeline-image-horizontal left top" src="images/1958-armstrong-x-15-photo.jpg" alt="Flying High. During re-entry from flight training at 207,000 feet in an X-15-3, Neil Armstrong inadvertently established a positive angle of attack during pull-out, and overshot Edwards Air Force Base in California, heading south at Mach 3 and 100,000 feet altitude. He finally managed to turn back while over the Rose Bowl in Pasadena, and had just enough energy to land on the south end of Rogers Dry Lake at Edwards. In the debriefing, someone asked how much clearance the X-15 had from the Joshua trees on the edge of the lakebed. &ldquo;Oh, at least 100 feet...on either side,&rdquo; said the chase pilot. Image Credit: NASA" />

				<img class="timeline-image-horizontal right-horizontal bottom" src="images/1958-armstrong-x-15-cockpit-photo.jpg" alt="1961. Neil in cockpit of X-15 at Dryden Flight Research Center. Image Credit: NASA" />

					<p class="timeline-image-horizontal left timeline-description-horizontal across bottom-desc">Flying High. During re-entry from flight training at 207,000 feet in an X-15-3, Neil Armstrong inadvertently established a positive angle of attack during pull-out, and overshot Edwards Air Force Base in California, heading south at Mach 3 and 100,000 feet altitude. He finally managed to turn back while over the Rose Bowl in Pasadena, and had just enough energy to land on the south end of Rogers Dry Lake at Edwards. In the debriefing, someone asked how much clearance the X-15 had from the Joshua trees on the edge of the lakebed. &ldquo;Oh, at least 100 feet...on either side,&rdquo; said the chase pilot. Image Credit: NASA</p>

			</li>
			<li>
				<h4 class="title">1958</h4>
				<h5 class="subtitle">He was selected for the U.S. Air Force's Man-In-Space Soonest program.</h5>

				<img class="timeline-image-vertical center-vertical middle" src="images/1958-armstrong-nasa-photo.jpg" alt="A portrait of Neil Armstrong while a test pilot at the NACA High-Speed Flight Station at Edwards Air Force Base, California. 20 November 1956. Photo Credit: NASA" />
					<p class="timeline-image-vertical center-vertical timeline-description-vertical middle-desc">A portrait of Neil Armstrong while a test pilot at the NACA High-Speed Flight Station at Edwards Air Force Base, California. 20 November 1956. Photo Credit: NASA</p>

			</li>
			<li>
				<h4 class="title">1962</h4>
				<h5 class="subtitle">He joined the NASA Astronaut Corps (Group 2), which the press dubbed &ldquo;The New Nine.&rdquo;</h5>

					<img class="timeline-image-horizontal center-horizontal middle" src="images/1962-the-new-nine.jpg" alt="Nine new flight personnel selected by Manned Spacecraft Center, National Aeronautics and Space Administration, in Houston Sept 17, 1962, are front row, left to right, Navy Lt. Charles Conrad, Jr., Air Force Major Frank Borman; NASA Test Pilot Neil Armstrong, and Navy Lt. Cmdr. John W. Young; second row, civilian test pilot Elliott M. See, Jr., Air Force Capt. James A. McDivitt, Navy Lt. Cmdr. James A. Lovell, Jr., Air Force Capt. Edward H. White II, and Air Force Capt. Thomas P. Stafford. 17 September 1962. Photo credit: NASA" />

						<p class="timeline-image-horizontal left timeline-description-horizontal across middle-desc">Nine new flight personnel selected by Manned Spacecraft Center, National Aeronautics and Space Administration, in Houston Sept 17, 1962, are front row, left to right, Navy Lt. Charles Conrad, Jr., Air Force Major Frank Borman; NASA Test Pilot Neil Armstrong, and Navy Lt. Cmdr. John W. Young; second row, civilian test pilot Elliott M. See, Jr., Air Force Capt. James A. McDivitt, Navy Lt. Cmdr. James A. Lovell, Jr., Air Force Capt. Edward H. White II, and Air Force Capt. Thomas P. Stafford. 17 September 1962. Photo credit: NASA</p>
			</li>

			<li>
				<h4 class="title">1966</h4>
				<h5 class="subtitle">He was the command pilot for Gemini 8, completing the first successful docking between two spacecraft in orbit, but suffered the first critical in-space system failure of a U.S. spacecraft.</h5>

					<img class="timeline-image-vertical left top" src="images/1966-armstrong-boarding-gemini-viii-photo.jpg" alt="Boarding Gemini VIII, Commander Neil Armstrong (right) and pilot David R. Scott prepare to board the Gemini-Titan VIII. Gemini VIII successfully launched at 11:41 a.m. EST, March 16, 1966. The mission conducted the first docking of two spacecraft in orbit and landed safely back on Earth after an emergency abort. Image Credit: NASA" />

						<p class="timeline-image-vertical left timeline-description-vertical top-desc-vert tall">Boarding Gemini VIII, Commander Neil Armstrong (right) and pilot David R. Scott prepare to board the Gemini-Titan VIII. Gemini VIII successfully launched at 11:41 a.m. EST, March 16, 1966. The mission conducted the first docking of two spacecraft in orbit and landed safely back on Earth after an emergency abort. Image Credit: NASA</p>

					<img class="timeline-image-vertical right-vertical bottom" src="images/1966-armstrong-inside-gemini-viii-photo.jpg" alt="Neil Armstrong on the Gemini 8 mission in 1966. Image Credit: NASA" />

						<p class="timeline-image-vertical right-vertical timeline-description-vertical narrow bottom-desc">Neil Armstrong on the Gemini 8 mission in 1966. Image Credit: NASA</p>
			</li>

			<li>
				<h4 class="title">1968</h4>
				<h5 class="subtitle">He survived an Apollo 11 training accident with the Lunar Landing Research Vehicle.</h5>

					<img class="timeline-image-vertical left top" src="images/1968-armstrong-LLRV.jpg" alt="Neil Armstrong at the Lunar Landing Research Facility (LLRF). Image Credit: NASA" />

						<p class="timeline-image-vertical left timeline-description-vertical narrower top-desc-vert">Neil Armstrong at the Lunar Landing Research Facility (LLRF). Image Credit: NASA</p>

					<div class="iframe close-call bottom"><script title="Armstrong's Close Call. A fiery bailout while training to land on the moon. Video: NASA" src="http://player.ooyala.com/player.js?deepLinkEmbedCode=RyYWdxOuPhBj0tIK6lrB0rjTkWKugRqg&amp;embedCode=RyYWdxOuPhBj0tIK6lrB0rjTkWKugRqg&amp;height=315&amp;video_pcode=ZnM2U6KMaWgHJof9G_au2_GdWAWT&amp;width=300" type="text/javascript"></script></div>

			</li>

			<li>
				<h4 class="title">1969</h4>
				<h5 class="subtitle">July 20. As Commander of Apollo 11, he successfully landed the Lunar Lander on the moon, and became the first man on the moon.</h5>

					<img class="timeline-image-horizontal left top" src="images/1969-apollo-11-crew.jpg" alt="Apollo 11 Crew
The Apollo 11 lunar landing mission crew, pictured from left to right, Neil A. Armstrong, commander; Michael Collins, command module pilot; and Edwin E. Aldrin Jr., lunar module pilot. Image Credit: NASA" />

						<p class="timeline-image-horizontal left timeline-description-horizontal top-desc">Apollo 11 Crew
The Apollo 11 lunar landing mission crew, pictured from left to right, Neil A. Armstrong, commander; Michael Collins, command module pilot; and Edwin E. Aldrin Jr., lunar module pilot. Image Credit: NASA</p>

					<iframe class="iframe bottom" width="420" height="315" src="http://www.youtube.com/embed/xSdHina-fTk?rel=0" title="One Small Step, One Giant Leap. Video: NASA" allowfullscreen></iframe>
			</li>

			<li>
				<h4 class="title">1970</h4>
				<h5 class="subtitle">After Apollo 11, he became an executive at NASA as Deputy Associate Administrator for Aeronautics for the Office of Advanced Research and Technology.</h5>

				<img class="timeline-image-horizontal center-horizontal middle" src="images/apollo-11-crew-in-quarantine.jpg" alt="President Richard M. Nixon was in the central Pacific recovery area to welcome the Apollo 11 astronauts aboard the U.S.S. Hornet, prime recovery ship for the historic Apollo 11 lunar landing mission. Already confined to the Mobile Quarantine Facility (MQF) are (left to right) Neil A. Armstrong, commander; Michael Collins, command module pilot; and Edwin E. (&ldquo;Buzz&rdquo;) Aldrin Jr., lunar module pilot. The three crewmen will remain in the MQF until they arrive at the Manned Spacecraft Center's (MSC) Lunar Receiving Laboratory (LRL). 24 July 1969. Photo Credit: NASA" />

					<p class="timeline-image-horizontal left timeline-description-horizontal across middle-desc">President Richard M. Nixon was in the central Pacific recovery area to welcome the Apollo 11 astronauts aboard the U.S.S. Hornet, prime recovery ship for the historic Apollo 11 lunar landing mission. Already confined to the Mobile Quarantine Facility (MQF) are (left to right) Neil A. Armstrong, commander; Michael Collins, command module pilot; and Edwin E. (&ldquo;Buzz&rdquo;) Aldrin Jr., lunar module pilot. The three crewmen will remain in the MQF until they arrive at the Manned Spacecraft Center's (MSC) Lunar Receiving Laboratory (LRL). 24 July 1969. Photo Credit: NASA</p>
			</li>

			<li>
				<h4 class="title">1971</h4>
				<h5 class="subtitle">He resigned from NASA and became a University Professor of Aerospace Engineering at the University of Cincinnati.</h5>

					<img class="timeline-image-horizontal left top" src="images/uc-armstrong-1974-teaching.jpg" alt="Armstrong teaching engineering students in 1974. Photo taken by Peggy Palange, UC Public Information Office" />

						<p class="timeline-image-horizontal left timeline-description-horizontal">Armstrong teaching engineering students in 1974. Photo taken by Peggy Palange, UC Public Information Office</p>

					<img class="timeline-image-horizontal right-horizontal bottom" src="images/uc-armstrong-1972-with-eng-colleagues.jpg" alt="Taking a Break. Armstrong (center with a pipe) talks to UC Department of Aerospace Engineering faculty in 1972. Photo credit: UC Public Information Office" />

						<p class="timeline-image-horizontal right-horizontal timeline-description-horizontal">Taking a Break. Armstrong (center with a pipe) talks to UC Department of Aerospace Engineering faculty in 1972. Photo credit: UC Public Information Office</p>
			</li>

			<li>
				<h4 class="title">1979</h4>
				<h5 class="subtitle">He left the University of Cincinnati to pursue other activities as well as to serve on numerous corporate boards.</h5>

					<img class="timeline-image-vertical center-vertical middle award" src="images/armstrong-ambassador-award-cinci-museum-center.jpg" alt="NASA Administrator Michael Griffin presented the NASA Ambassadors of Exploration award to Neil Armstrong. He received the award that includes a moon rock to recognize the sacrifices and dedication of the astronauts and others who were part of the Mercury, Gemini and Apollo programs.The Cincinnati Museum Center at Union Terminal. Photo Credit: NASA/Bill Ingalls" />

						<p class="timeline-image-vertical center-vertical timeline-description-vertical wide middle-desc tall award-desc">NASA Administrator Michael Griffin presented the NASA Ambassadors of Exploration award to Neil Armstrong. He received the award that includes a moon rock to recognize the sacrifices and dedication of the astronauts and others who were part of the Mercury, Gemini and Apollo programs. The Cincinnati Museum Center at Union Terminal. Photo Credit: NASA/Bill Ingalls</p>
			</li>

			<li>
				<h4 class="title">2012</h4>
				<h5 class="subtitle">Neil Armstrong died on August 25, 2012.</h5>

				<img class="timeline-image-horizontal center-horizontal middle" src="images/2012-armstrong-burial-at-sea.jpg" alt="Members of the US Navy ceremonial guard hold an American flag over the cremains of Apollo 11 astronaut Neil Armstrong during a burial at sea service aboard the USS Philippine Sea (CG 58), Friday, Sept. 14, 2012, in the Atlantic Ocean. Armstrong, the first man to walk on the moon during the 1969 Apollo 11 mission, died Saturday, Aug. 25. He was 82. Photo Credit: (NASA/Bill Ingalls)" />

					<p class="timeline-image-horizontal left timeline-description-horizontal across middle-desc">Members of the US Navy ceremonial guard hold an American flag over the cremains of Apollo 11 astronaut Neil Armstrong during a burial at sea service aboard the USS Philippine Sea (CG 58), Friday, Sept. 14, 2012, in the Atlantic Ocean. Armstrong, the first man to walk on the moon during the 1969 Apollo 11 mission, died Saturday, Aug. 25. He was 82. Photo Credit: (NASA/Bill Ingalls)</p>
			</li>
		</ul>

		<ul id="timeline-pagination" class="sequence-pagination">
			<li><span>1930</span></li>
			<li><span>1936</span></li>
			<li><span>1939</span></li>
			<li><span>1947</span></li>
			<li><span>1950</span></li>
			<li><span>1955</span></li>
			<li><span>1958</span></li>
			<li><span>1958</span></li>
			<li><span>1962</span></li>
			<li><span>1966</span></li>
			<li><span>1968</span></li>
			<li><span>1969</span></li>
			<li><span>1970</span></li>
			<li><span>1971</span></li>
			<li><span>1979</span></li>
			<li><span>2012</span></li>
		</ul>

	</div>

</div><!--end section sequence-theme-->
