<div class="on-uc-campus-supporting-info">
	
	<!--2013 dedication event youTube video-->	
	<iframe class="exhibit" width="560" height="315" src="https://www.youtube.com/embed/BZG71PLwWAY?wmode=transparent" frameborder="0" allowfullscreen></iframe>

	<!--2013 dedication event text-->
	<div class="exhibit-subtitle">
		<h3>HONORING NEIL ARMSTRONG AT UC</h3>
			<p>The University of Cincinnati announced on Nov. 6, 2013 the vision for a Neil Armstrong Space Science Institute and an important research partnership with NASA's Ames Research Center while also honoring the life of Neil Armstrong, who taught at UC from 1971 to 1979.<br/ > <a class="link-icon"  href="http://www.uc.edu/news/NR.aspx?id=18747">Read more at UC News</a></p>		
	</div>
	
</div><!--end on-uc-campus-supporting-info-->			

	
