<div id="armstrong-the-man" class="parallax-bkgrnd section">
    	
	<img id="armstrong-the-man-log-book" src="images/armstrong-log-book-pages.png" alt="Aviators Flight Log Book, Neil Armstrong, USNR, 1949 and personal photos from the UC Neil Armstrong Commemorative Archives Collection. Astronaut photo courtesy of NASA." />
		
	<div id="armstrong-the-man-header">
		<h2> Armstrong, the Man</h2>            
	</div><!--end the-man-header-->    	
	
	<h3 class="hidden">Neil Armstrong Biography Courtesy of NASA</h3>
	<div id="bio-text">
		<div>
		<p>Neil A. Armstrong, the first man to walk on the moon, was born in Wapakoneta, Ohio,
	on August 5, 1930. He began his NASA career in Ohio.</p>
		<p>After serving as a naval aviator from 1949 to 1952, Armstrong joined the National Advisory Committee for Aeronautics (NACA) in 1955. His first assignment was with the NACA Lewis Research Center (now NASA Glenn) in Cleveland. Over the next 17 years, he was an engineer, test pilot, astronaut and administrator for NACA and its successor agency, the National Aeronautics and Space Administration (NASA).</p> 
		<p>As a research pilot at NASA's Flight Research Center, Edwards, Calif., he was a project pilot on many pioneering high speed aircraft, including the well known, 4000-mph X-15. He has flown over 200 different models of aircraft, including jets, rockets, helicopters and gliders.</p>
		<p>Armstrong transferred to astronaut status in 1962. He was assigned as command pilot for the Gemini 8 mission. Gemini 8 was launched on March 16, 1966, and Armstrong performed the first successful docking of two vehicles in space.</p>
		<p>As spacecraft commander for Apollo 11, the first manned lunar landing mission, Armstrong gained the distinction of being the first man to land a craft on the moon and first to step on its surface.</p>
		<p>Armstrong subsequently held the position of Deputy Associate Administrator for Aeronautics, NASA Headquarters, Washington, D.C. In this position, he was responsible for the coordination and management of overall NASA research and technology work related to aeronautics.</p>
		<p>He was Professor of Aerospace Engineering at the University of Cincinnati between 1971-1979. During the years 1982-1992, Armstrong was chairman of Computing Technologies for Aviation, Inc., Charlottesville, Va.</p>
		<p>He received a Bachelor of Science Degree in Aeronautical Engineering from Purdue University and a Master of Science in Aerospace Engineering from the University of Southern California. He holds honorary doctorates from a number of universities.</p>
		<p>Armstrong was a Fellow of the Society of Experimental Test Pilots and the Royal Aeronautical Society; Honorary Fellow of the American Institute of Aeronautics and Astronautics, and the International Astronautics Federation.</p>
		<p>He was a member of the National Academy of Engineering and the Academy of the Kingdom of Morocco. He served as a member of the National Commission on Space (1985-1986), as Vice-Chairman of the Presidential Commission on the Space Shuttle Challenger Accident (1986), and as Chairman of the Presidential Advisory Committee for the Peace Corps (1971-1973).</p>
		<p>Armstrong was decorated by 17 countries. He was the recipient of many special honors, including the Presidential Medal of Freedom; the Congressional Gold Medal; the Congressional Space Medal of Honor; the Explorers Club Medal; the Robert H. Goddard Memorial Trophy; the NASA Distinguished Service Medal; the Harmon International Aviation Trophy; the Royal Geographic Society's Gold Medal; the Federation Aeronautique Internationale's Gold Space Medal; the American Astronautical Society Flight Achievement Award; the Robert J. Collier Trophy; the AIAA Astronautics Award; the Octave Chanute Award; and the John J. Montgomery Award.</p>
		<p>Armstrong passed away on Aug. 25, 2012 following complications resulting from cardiovascular procedures. He was 82.</p>
		
		<p class="author"><a class="link-icon" href="http://www.nasa.gov/centers/glenn/about/bios/neilabio.html" >Courtesy of NASA</a></p>
		</div>
	</div><!--end text-->
                 
</div><!--end section armstrong-the-man parallax-bkgrnd-->