<div id="armstrong-large-3d-objects-menu">
          
    <div id="large-3d-objects-menu" class="armstrong-nav clearfix">  
        <ul class="clearfix">  
			<li><a href="armstrong-flight-mask.html">Flight Mask</a></li>
            <li><a href="armstrong-gemini-heat-shield.html">Gemini Heat Shield</a></li>  
            <li><a href="armstrong-artificial-hip.html">Artificial Hip</a></li> 
		</ul>
		<ul class="clearfix"> 
            <li><a href="armstrong-flight-award.html">Freedom of Flight Award</a></li>
       	    <li><a href="armstrong-metal-disc.html">Ballistic Particle Test, Metal Disc</a></li>  
            <li><a href="armstrong-chamber-award.html">Cincinnati Chamber of Commerce Award</a></li>      
        </ul>  
        
    </div><!--end large-3d-objects-menu armstrong-nav clearfix--> 
            
</div><!--end armstrong-nav-menu--> 
