    <!--begin about the project page-->
<div id="about">
  
	<h2 class="center">About the<br /> Commemorative Website</h2>    
    
	    <div class="funding">
			
			<p>Funding for the Neil Armstrong Commemorative Website project provided through the generous support of University of Cincinnati President Santa Ono and former Interim Senior Vice President for Academic Affairs and Provost, Larry Johnson.</p>
   		</div>
	
		<div class="about-section">
			
			<h3 class="essay-title">CONTACT INFO</h3>
		
				<h4>Ted Baldwin</h4>
						<p><span>Director, Science and Engineering Library</span><br />
						513-556-4211 or <a class="mail" href="mailto:Ted.Baldwin@uc.edu?Subject=Neil%20Armstrong%20Commemorative%20Website" >Ted.Baldwin@uc.edu</a></p>
		</div>
	
		<div class="about-section">
			
			<h3 class="essay-title">Neil Armstrong Commemorative Website Project Team (University of Cincinnati Libraries)</h3>
		
				<ul>
					<li>
						<h4>Ted Baldwin</h4> 
						<p><span>Project Director</span></p>
					</li>
					<li>
						<h4>Kevin Grace</h4> 
						<p><span>University Archivist</span></p>
					</li>
					<li>
						<h4>Carrie Hill-Harriss</h4> 
						<p><span>Website Design and Research</span></p>
					</li>
					<li>
						<h4>Linda Newman</h4> 
						<p><span>Technology Leader</span></p>
					</li>
					<li>
						<h4>Steve Marine</h4> 
						<p><span>Project Advisor</span></p>
					</li>		
				</ul>
		</div>
    
		<div class="about-section">
			
			<h3 class="essay-title">Other Contributors to this Project</h3>
		
				<ul>
					<li>
						<h4>John Bach</h4> 
						<p><span>UC Magazine</span></p>
					</li>
					<li>
						<h4>Maitreya Dutta</h4> 
						<p><span>Digital Collections, UC Libraries</span></p>
					</li>
					<li>
						<h4>Angela Klocke</h4> 
						<p><span>UC Creative Services</span></p>
					</li>
					<li>
						<h4>Kerry Overstake</h4> 
						<p><span>Web Communications</span></p>
					</li>
					<li>
						<h4>Janice Schulz</h4> 
						<p><span>Archives and Rare Books Library</span></p>
					</li>	
					<li>
						<h4>Jay Yocis</h4> 
						<p><span> University Communications</span></p>
					</li>
						
				</ul>
		</div> 
		
		<div class="funding thank-you">
			<p>Thank you to the <a href="http://www.lloydlibrary.org" >Lloyd Library and Museum Archives</a> for contributing materials from George Rieveschl, Jr. Papers related to Professor Armstrong and the HARP research group.</p>
			<p>Thank you to UC alumni Bob Levo, BS AsE '77, and Mark Stear, BS AsE '78, for sharing images from their time at UC with Professor Armstrong.</p>	 		
   		</div>
</div>
<!--end learn more page-->
