<div id="uc-photo-gallery" class="section">
	<h3 class="title">His Time at UC 1971-1979 Gallery</h3>
	<div class="sequence-theme-uc-gallery">
		<div id="sequence-uc-gallery" class="sequence">
	
			<img class="sequence-prev" src="images/button-arrow-prev.png" alt="Previous Frame" />
			<img class="sequence-next" src="images/button-arrow-next.png" alt="Next Frame" />
	
			<ul class="sequence-canvas">
				<li class="animate-in">
				
					<h4 class="hidden">Professor Armstrong and the HARP Group</h4>
					
						<p class="subtitle">The HARP Group: Neil Armstrong, George Rieveschl, Henry Heimlich and Edward Patrick <a class="link-icon" href="http://libapps.libraries.uc.edu/liblog/2012/09/11/dr-h-j-heimlich-project-working-with-neil-armstrong/" >Read more about the HARP Group at the UC Dr. H. J. Heimlich Blog&hellip;</a> Photo courtesy of Kevin Grace, Head and University Archivist, UC Archives and Rare Books Library.
						<br /><a class="link-icon" href="http://hdl.handle.net/2374.UC/745155" >Read the HARP Apollo Diaphram Pump abstract created for a 1975 presentation in the UC Neil Armstrong Commemorative Archives.</a></p>
						
						<img class="gallery-image gallery-image-horizontal" src="images/uc-armstrong-harp.jpg" 
							alt="The HARP Group: Neil Armstrong, George Rieveschl, Henry Heimlich and Edward Patrick. Photo courtesy of Kevin Grace, Head and University Archivist, UC Archives and Rare Books Library"  />
				
					
				</li>
				
				<li>
					<h4 class="hidden">Professor Armstrong and the HARP Group&rsquo;s Apollo Double Diaphram Pump</h4> 
					
						<p class="subtitle"><a class="link-icon" href="http://hdl.handle.net/2374.UC/730754" >Read more about the Apollo Double Diaphram Pump (ADDP), perfected by the HARP group (Neil Armstrong, Henry Heimlich, Edward Patrick, and George Rieveschl) in the UC News Record April,1975 article, &ldquo;UC researchers perfect NASA artificial heart pump&rdquo; in the UC Neil Armstrong Commemorative Archives Collection.</a></p>
						
						<img class="gallery-image gallery-image-horizontal" src="images/uc-news-record-heart-pump-article.jpg" alt="Read more about the Apollo Double Diaphram Pump (ADDP), perfected by the HARP group (Neil Armstrong, Henry Heimlich, Edward Patrick, and George Rieveschl) in this UC News Record April,1975 article, &ldquo;UC researchers perfect NASA artificial heart pump&rdquo; in the UC Neil Armstrong Commemorative Archives Collection." />
					
				</li> 
		
				<li>
				
					<h4 class="hidden">Professor Armstrong Taking a Break With Faculty in 1972</h4>
					
						<p class="subtitle">Taking a Break. Armstrong (center with a pipe) talks to UC Department of Aerospace Engineering faculty in 1972. 
						Photo credit: UC Public Information Office</p>
						
						<img class="gallery-image gallery-image-horizontal" src="images/uc-armstrong-1972-with-eng-colleagues.jpg" alt="Taking a Break. Armstrong (center with a pipe) talks to UC Department of Aerospace Engineering faculty in 1972. Photo credit: UC Public Information Office" />
				</li>
				
				<li>
				
					<h4 class="hidden">Professor Armstrong listening to Visitor in 1973</h4>
					
						<p class="subtitle">Armstrong listens to visitor from a Republic of China delegation at UC in 1973. (UC photo)</p>
						
						<img class="gallery-image gallery-image-horizontal" src="images/uc-armstrong-1973-with-chinese-colleague.jpg" alt="Armstrong listens to visitor from a Republic of China delegation at UC in 1973. (UC photo)" />
				</li>
				
				<li>
				
					<h4 class="hidden">Professor Armstrong Creating a Paper Airplane on Campus in 1974</h4>
					
						<p class="subtitle">Armstrong creates a paper airplane at an event hosted by the American Institute of Aeronautics and Astronautics student chapter. Photo credit: Ralph Spitzen (Eng '74, MBA '76).</p>
						
						<img class="gallery-image gallery-image-horizontal" src="images/uc-armstrong-1974-paper-airplane-event.jpg" alt="Armstrong creates a paper airplane at an event hosted by the American Institute of Aeronautics and Astronautics student chapter. Photo credit: Ralph Spitzen (Eng &rsquo;74, MBA &rsquo;76)." />
				</li>
				
				<li>
				
					<h4 class="hidden">Professor Armstrong Creating a Paper Airplane on Campus in 1974</h4>
					
						<p class="subtitle vertical">Armstrong creates a paper airplane at an event hosted by the American Institute of Aeronautics and Astronautics student chapter. Photo credit: Ralph Spitzen (Eng '74, MBA '76)</p>
						
						<img class="gallery-image gallery-image-vertical" src="images/uc-armstrong-1974-paper-airplane-event-2.jpg" alt="Armstrong creates a paper airplane at an event hosted by the American Institute of Aeronautics and Astronautics student chapter. Photo credit: Ralph Spitzen (Eng &rsquo;74, MBA &rsquo;76)" />
				</li>
				
				<li>
				
					<h4 class="hidden">Professor Armstrong Teaching in 1974</h4>
					
						<p class="subtitle">Armstrong teaching engineering students in 1974. Photo credit: Peggy Palange, UC Public Information Office</p>
						
						<img class="gallery-image gallery-image-horizontal" src="images/uc-armstrong-1974-teaching.jpg" alt="Armstrong teaching engineering students in 1974. Photo credit: Peggy Palange, UC Public Information Office" />
				</li>
				
				<li>
				
					<h4 class="hidden">Professor Armstrong Writing on Chalkboard in 1974</h4>
					
						<p class="subtitle">In 1974, Neil Armstrong writes on a chalkboard in the UC College of Engineering. Photo Credit: Peggy Palange, UC Public Information Office</p>
						
						<img class="gallery-image gallery-image-horizontal" src="images/uc-armstrong-1974-at-blackboard.jpg" alt="In 1974, Neil Armstrong writes on a chalkboard in the UC College of Engineering. Photo Credit: UC" />
				</li>
				
				<li>
				
					<h4 class="hidden">Professor Armstrong greeting Snoopy character at event in 1975</h4>
					
						<p class="subtitle">Armstrong greets Snoopy as part of an event hosted by the American Institute of Aeronautics and Astronautics student chapter in 1975. "Don't you agree his smile is terrific?" asks photographer Ralph Spitzen, Eng '74, MBA '76.</p>
						
						<img class="gallery-image gallery-image-horizontal" src="images/uc-armstrong-1975-with-snoopy.jpg" alt="Armstrong greets Snoopy as part of an event hosted by the American Institute of Aeronautics and Astronautics student chapter in 1975. &ldquo;Don't you agree his smile is terrific&#63;&rdquo; asks photographer Ralph Spitzen, Eng &rsquo;74, MBA &rsquo;76." />
				</li>
				
				<li>
				
					<h4 class="hidden">Professor Armstrong and the Flight Test Engineering II Class in 1977</h4>
				
						<p class="subtitle">Professor Armstrong and the Flight Test Engineering II Class. May, 1977. Left to right: Professor Neil Armstrong, Bill Stange, Bob Levo, Steve McCormick?, Dave Gomez, Dave Glock, Russ Claus, Dave Turner?, Don Benko, Dave Humphries, Tom Black. Photo courtesy of Bob Levo, UC '77 AsE, via Tom Black</p>
						
						<img class="gallery-image gallery-image-horizontal" src="images/uc-armstrong-1977-flight-test-eng-class-lunken.jpg" alt="Professor Armstrong and the Flight Test Engineering II Class. May, 1977. Left to right: Professor Neil Armstrong, Bill Stange, Bob Levo, Steve McCormick&#63;, Dave Gomez, Dave Glock, Russ Claus, Dave Turner&#63;, Don Benko, Dave Humphries, Tom Black. Photo courtesy of Bob Levo, UC &rsquo;77 AsE, via Tom Black" />
				</li>
				
				<li>
				
					<h4 class="hidden">Professor Armstrong and the Flight Test Engineering II Class at Lunken Airport in 1977</h4>
					
						<p class="subtitle">Professor Armstrong and the Flight Test Engineering II Class Spring 1977 at Lunken Airport. Photo courtesy of Bob Levo, UC '77 AsE</p>
						
						<img class="gallery-image gallery-image-horizontal" src="images/uc-armstrong-1977-flight-test-eng-class-lunken-airplane.jpg" alt="Professor Armstrong and the Flight Test Engineering II Class Spring 1977 at Lunken Airport. Photo courtesy of Bob Levo, UC &rsquo;77 AsE" />
				</li>
				
				<li>
				
					<h4 class="hidden">Professor Neil Armstrong at Lunken airport with the Flight Test Engineering II Class 1977</h4>
						
						<p class="subtitle">Professor Neil Armstrong at Lunken airport with the Flight Test Engineering II Class Spring 1977 in May of 1977. Photo courtesy of  Bob Levo, UC '77 AsE</p>
						
						<img class="gallery-image gallery-image-horizontal" src="images/neil-armstrong-at-lunken-airport-may-1977.jpg" alt="Professor Neil Armstrong at Lunken airport with the Flight Test Engineering II Class Spring 1977 in May of 1977. Photo courtesy of  Bob Levo, UC &rsquo;77 AsE" />
				</li>
				
				<li>
				
					<h4 class="hidden">Professor Neil Armstrong Class Handout on Airspeed Summary, 1977</h4>
					
						<p class="subtitle">Professor Neil Armstrong class handout on airspeed summary, for Aircraft Flight Testing class at University of Cincinnati, held winter quarter 1977. Written by Professor Armstrong, provided by Bob Levo, '77 AsE.
							<a class="link-icon"  href="http://hdl.handle.net/2374.UC/730956">Read these class notes, written by Neil Armstrong, and the description of the material by his former UC student, Bob Levo, UC &rsquo;77 AsE.</a></p>
						
						<img class="gallery-image gallery-image-horizontal" src="images/armstrong-class-handout-airspeed-1977.jpg" alt="Neil Armstrong class handout on airspeed summary, for Aircraft Flight Testing class at University of Cincinnati, held winter quarter 1977. Class handout provided by Bob Levo, UC &rsquo;77 AsE." />
				</li>
				
				<li>
				
					<h4 class="hidden">Professor Neil Armstrong Class Handout on Compressible Airspeed Theory, 1977</h4>
				
						<p class="subtitle">Professor Neil Armstrong class handout on compressible airspeed theory, for Aircraft Flight Testing class at University of Cincinnati, held winter quarter 1977. Written by Professor Armstrong, provided by Bob Levo, UC '77 AsE.
							<a class="link-icon"  href="http://hdl.handle.net/2374.UC/730986">Read these class notes, written by Neil Armstrong, and the description of the material by his former UC student, Bob Levo, UC &rsquo;77 AsE.</a></p>
						
						<img class="gallery-image gallery-image-horizontal" src="images/armstrong-class-handout-compressible-airspeed-1977.jpg" alt="Neil Armstrong class handout on compressible airspeed theory, for Aircraft Flight Testing class at University of Cincinnati, held winter quarter 1977. Written by Professor Armstrong, provided by Bob Levo, UC &rsquo;77 AsE." />
				</li>
				
				<li>
				
					<h4 class="hidden">Professor Neil Armstrong Class Handout on Dihedral, 1977</h4>
									
						<p class="subtitle">Professor Neil Armstrong class handout on dihedral, for Aircraft Flight Testing class at University of Cincinnati, held spring quarter 1977. Written by Professor Armstrong, provided by Bob Levo, UC '77 AsE.
							<a class="link-icon"  href="http://hdl.handle.net/2374.UC/731007">Read these class notes, written by Neil Armstrong, and the description of the material by his former UC student, Bob Levo, UC &rsquo;77 AsE.</a></p>
						
						<img class="gallery-image gallery-image-horizontal" src="images/armstrong-class-handout-wing-dihedral-1977.jpg" alt="Professor Neil Armstrong class handout on dihedral, for Aircraft Flight Testing class at University of Cincinnati, held spring quarter 1977. Written by Professor Armstrong, provided by Bob Levo, UC &rsquo;77 AsE." />
				</li>
				
				<li>
				
					<h4 class="hidden">Professor Neil Armstrong Class Handout on Maneuver Margins, 1977</h4>
					
						<p class="subtitle">Professor Neil Armstrong class handout on maneuver margins, for Aircraft Flight Testing class at University of Cincinnati, held spring quarter 1977. Written by Professor Armstrong, provided by Bob Levo, UC '77 AsE.
							<a class="link-icon"  href="http://hdl.handle.net/2374.UC/730957">Read these class notes, written by Neil Armstrong, and the description of the material by his former UC student, Bob Levo, UC &rsquo;77 AsE.</a></p>
						
						<img class="gallery-image gallery-image-horizontal" src="images/armstrong-class-handout-maneuver-margins-1977.jpg" alt="Professor Neil Armstrong class handout on maneuver margins, for Aircraft Flight Testing class at University of Cincinnati, held spring quarter 1977. Written by Professor Armstrong, provided by Bob Levo, UC &rsquo;77 AsE." />
				</li>
					
			   <li>
			   
			   		<h4 class="hidden">Professor Neil Armstrong at UC Press Conference in 1979</h4>
					
						<p class="subtitle">Neil Armstrong speaks at his only UC press conference, marking the 10th anniversary of the moon landing in 1979. Photo/Peggy Palange, UC Public Information Office</p>
						
						<img class="gallery-image gallery-image-horizontal" src="images/uc-armstrong-1979-press-conference.jpg" alt="Neil Armstrong speaks at his only UC press conference, marking the 10th anniversary of the moon landing in 1979. Photo/Peggy Palange, UC Public Information Office" />
				</li> 
				
				<li>
				
					<h4 class="hidden">Professor Neil Armstrong at UC in 1979</h4>
					
						<p class="subtitle">Professor Armstrong in March 1979. Photo credit: Peggy Palange, UC Public Information Office</p>
						
						<img class="gallery-image gallery-image-horizontal" src="images/uc-armstrong-1979-casual-portrait.jpg" alt="Professor Armstrong in March 1979. Photo credit: Peggy Palange, UC Public Information Office" />
				</li> 
				
				<li>
				
					<h4 class="hidden">Professor Armstrong at his UC desk in 1979</h4>
					
						<p class="subtitle">Professor Armstrong at his UC desk in 1979, behind a model NASA aircraft. Photo Credit: Peggy Palange, UC Public Information Office</p>
						
						<img class="gallery-image gallery-image-horizontal" src="images/uc-armstrong-1979-at-desk.jpg" alt="Armstrong at his UC desk in 1979, behind a model NASA aircraft. Photo Credit: Peggy Palange, UC Public Information Office" />
				</li>	
				
				<li>
				
					<h4 class="hidden">Neil Armstrong with Co-Pilot, Peter Reynolds, in Learjet Longhorn 28 in 1979</h4>
										
						<p class="subtitle">In February 1979, Neil Armstrong climbed to 50,000 feet in the Learjet Longhorn 28, setting five world records for business jets. His copilot is Peter Reynolds. Photo Courtesy of UC Magazine. 
							<a class="link-icon"  href="http://hdl.handle.net/2374.UC/713955">Read the 1979 News Release from the Gates Learjet Corporation in the UC Neil Armstrong Commemorative Archives Collection.</a></p>
						
						<img class="gallery-image gallery-image-horizontal" src="images/uc-armstrong-reynolds-learjet-1979.jpg" alt="In February 1979, Neil Armstrong climbed to 50,000 feet in the Learjet Longhorn 28, setting five world records for business jets. His copilot is Peter Reynolds. Photo Courtesy of UC Magazine." />
				</li>
				
				<li>
				
					<h4 class="hidden">Learjet Longhorn 28 Takes Off From &ldquo;First Flight&rdquo; Strip in 1979</h4>
				
						<p class="subtitle">Learjet Longhorn 28 takes off from &ldquo;First Flight&rdquo; strip near Kill Devil Hills, N.C. on record time-to-climb flight February 19, 1979. Photo Courtesy of UC Public Information Office. 
							<a class="link-icon"  href="http://hdl.handle.net/2374.UC/713955">Read the 1979 News Release from the Gates Learjet Corporation in the UC Neil Armstrong Commemorative Archives Collection.</a></p>
						
						<img class="gallery-image gallery-image-horizontal" src="images/uc-armstrong-lear-takeoff.jpg" alt="Learjet Longhorn 28 takes off from &ldquo;First Flight&rdquo; strip near Kill Devil Hills, N.C. on record time-to-climb flight February 19, 1979. Four other world records for altitude, and sustained altitude at 51,000 feet were set during two-day period. Photo Courtesy of UC Public Information Office." />
				</li>
				
				<li>
				
					<h4 class="hidden">Neil Armstrong, left, Mark Stear, and Pete Reynolds review the results of one of the trial runs at Learjet, February 1979</h4>
					
						<p class="subtitle">Neil Armstrong, left, Mark Stear, and Pete Reynolds review the results of one of the trial runs at Learjet, February 1979. Photo Courtesy of Mark Stear, BSAsE, '78. 
							<a class="link-icon"  href="http://hdl.handle.net/2374.UC/713955">Read the 1979 News Release from the Gates Learjet Corporation in the UC Neil Armstrong Commemorative Archives Collection.</a></p>
						
						
						<img class="gallery-image gallery-image-horizontal" src="images/uc-armstrong-time-to-climb-1979.jpg" alt="Neil Armstrong, left, Mark Stear, and Pete Reynolds review the results of one of the trial runs at Learjet, February 1979. Photo Courtesy of Mark Stear, BSAsE, &rsquo;78. Featured in the Aerospace Engineering Newsletter, November 2012." />
				</li>
							
				<li>
				
					<h4 class="hidden">Gina Lollobrigida as a photographer, a few years earlier than she came looking for Armstrong at UC</h4>
						
					  <p class="subtitle vertical">Gina Lollobrigida as a photographer, a few years earlier than she came looking for Armstrong at UC.</p>
					  
					  <img class="gallery-image gallery-image-vertical" src="images/gina-lollabrigida-as-photographer.jpg" alt="Gina Lollobrigida as a photographer, a few years earlier than she came looking for Armstrong at UC." />
				</li>
				
				
	
			</ul>
	
		</div>            
	 </div>  
	<!--</div>--><!--end sequence-theme-->    
</div><!--end section time-at-uc-gallery-->
	
