



<div id="on-uc-campus-gallery">

 <!--on uc campus gallery-->



	<div id="sequence-theme-on-uc-campus"  class="section">

		<div id="sequence-on-uc-campus">

			<ul class="sequence-canvas">
				<li class="animate-in">
				<img src="images/uc-campus-ceas-exhibit.jpg" alt="The Armstrong Collection Exhibit located at the CEAS (College of Engineering and Applied Science) Library in Baldwin Hall on UC Campus" />
					<p id="exhibit-ceas" class="subtitle">OPENING FALL 2015<br />Located in Baldwin Hall, The Armstrong Collection at the College of Engineering and Applied Science Libary will feature objects and papers from the UC Commemorative Archives. <a class="link-icon" href="http://www.uc.edu/content/dam/common/docs/maps/campus_map_west_color.pdf">Visit UC Campus</a></p>

					<h2>On UC Campus</h2>
				</li>

				<li>
					<p id="exhibit-rhodes" class="subtitle">This bas-relief by local artist John Leon shows Neil Armstrong folding a paper airplane inside UC’s Armory Fieldhouse. The photo used for the artwork was taken by UC alumnus Ralph Spitzen in 1974. The piece also includes a reprint of the New York Times coverage of Armstrong’s first steps onto the lunar surface. The plaque is a gift of the class of 2013. <a class="link-icon" href="http://www.uc.edu/content/dam/common/docs/maps/campus_map_west_color.pdf">Visit UC Campus</a></p>
					<img src="images/uc-campus-rhodes-hall-memorial.jpg" alt="The bas-relief memorial located in Rhodes Hall on UC Campus" />
					<h2>On UC Campus</h2>
				</li>
			</ul>

			<ul id="on-uc-campus-pagination" class="sequence-pagination">
					<li><span>The Armstrong Collection<br />CEAS Library Exhibit</span></li>
					<li><span>Rhodes Hall<br />Armstrong Memorial</span></li>
			</ul>


		</div><!--end sequence-on-uc-campus-->


	</div><!--sequence-theme-on-uc-campus-->

</div><!--end on-uc-campus gallery section-->
