<h3 class="hidden">UC Magazine Articles about Neil Armstrong's Time at UC</h3>

<div id="uc-magazine-articles" class="section">

    <div id="articles-header">
		<!--uc magazine logo-->
		<a href="http://magazine.uc.edu/" ><img id="image-small-percentage" class="image-small" src="images/uc-magazine-icon.jpg" alt="UC Magazine" /></a>

		<!--article description text-->
		<div id="uc-magazine-description" title="Click on the images below to go to UC Magazine articles about Neil Armstrong's time at UC.">
			Click on the images below to go to UC Magazine articles about Neil Armstrong's time at UC.
		</div>
		<!--end article description text-->
    </div><!--end articles-header-->


    <!--begin article links-->
    <div id="armstrong-nav-articles" class="armstrong-nav clearfix">
        <ul class="clearfix">

            <li>
                <div class="article" data-description="Read these little-known insights which help tell how one small step led to a reluctant hero.">

					<a class="button-circle" id="article-farewell" href="http://magazine.uc.edu/issues/0413/Armstrong.html" >
						<h4 class="hidden">&ldquo;Farewell Neil Armstrong: UC's most famous, humble professor&rdquo; &mdash;UC Magazine</h4></a>
                </div>

            </li>

            <li>
                <div class="article" data-description="Read remembrances about the professor, Neil Armstrong, whom students and faculty knew.">
                    <a class="button-circle" id="article-prof-armstrong" href="http://magazine.uc.edu/editors_picks/recent_features/armstrong/remember.html" >
						<h4 class="hidden">&ldquo;Students, Faculty Remember Neil Armstrong&rdquo; &mdash;UC Magazine</h4></a>
                </div>

            </li>

            <li>
                <div class="article" data-description="Read about Neil Armstrong making his own paper airplane alongside students on UC Campus in 1974.">
                    <a class="button-circle" id="article-on-campus" href="http://magazine.uc.edu/issues/1011/oncampusyesterday.html" >
						<h4 class="hidden">&ldquo;On Campus Yesterday, 1974&rdquo; &mdash;UC Magazine</h4></a>
                </div>
            </li>

            <li>
                <div class="article" data-description="Read about his desire to teach and Gina Lollabrigita's visit to UC to photograph Neil Armstrong.">
                    <a class="button-circle" id="article-armstrong-1930-2012" href="http://magazine.uc.edu/editors_picks/recent_features/armstrong.html" >
						<h4 class="hidden">&ldquo;Memories of Neil Armstrong as a UC professor&rdquo; &mdash;UC Magazine</h4></a>
                </div>
            </li>

            <li>
                <div class="article" data-description="Read about Armstrong's close call in 1969 and how the professor's superb piloting skills served little purpose in an unmanned car.">
                    <a class="button-circle" id="article-wrecks" href="http://magazine.uc.edu/editors_picks/recent_features/armstrong/wrecks.html#lunar" >
						<h4 class="hidden">&ldquo;Neil Armstrong's Wrecks on Land, Near Wrecks in Space&rdquo; &mdash;UC Magazine</h4></a>
                </div>

            </li>

            <li>
                <div class="article" data-description="Read thoughts and observations on Armstrong's determination to have a private life.">
                    <a class="button-circle" id="article-average-guy" href="http://magazine.uc.edu/editors_picks/recent_features/armstrong/average.html" >
						<h4 class="hidden">&ldquo;UC Professor Neil Armstrong: &lsquo;Mr. Average Guy&rsquo;&rdquo; &mdash;UC Magazine</h4></a>
                </div>
            </li>
            <li>
                <div class="article" data-description="See the U.S. Customs declaration form signed by the Apollo 11 crew declaring moon rocks as cargo upon entering the U.S.">
                    <a class="button-circle" id="article-moon-rocks-customs" href="http://magazine.uc.edu/editors_picks/recent_features/armstrong/moonrocks.html" >
    					<h4 class="hidden">&ldquo;Neil Armstrong's Customs Form for Moon Rocks&rdquo; &mdash;UC Magazine</h4></a>
                </div>
            </li>
             <li>
                <div class="article" data-description="Read Neil Armstrong's UC Commencement address presented on June 13, 1982 while he was an adjunct professor at UC.">
                    <a class="button-circle" id="article-commencement-address" href="http://magazine.uc.edu/editors_picks/recent_features/armstrong/commencement.html" >
						<h4 class="hidden">&ldquo;Neil Armstrong's 1982 UC Commencement address&rdquo; &mdash;reprinted by UC Magazine</h4></a>
                </div>
            </li>
        </ul>

        <a href="#" class="pull" id="articles-pull">UC Articles</a>

    </div><!--end uc-magazine-articles-->
    <!--end article links-->

    <!--family quote-->
    <div id="family-statement-quote">
        <p class="page-subtitle">&ldquo;For those who may ask what they can do to honor Neil, we have a simple request. Honor his example of service, accomplishment and modesty, and the next time you walk outside on a clear night and see the moon smiling down at you, think of Neil Armstrong and give him a wink.&rdquo;</p>
            <p class="quote-source">&mdash;from the family of Neil Armstrong's statement upon his passing. August 25, 2012</p>
    </div><!--end family-statement-quote-->

</div><!--end section uc-magazine-articles-->
