<h2 class="hidden">The Armstrong Collection</h2>

	<h3 class="hidden">The Armstrong Collection Gallery</h3>

<div id="collection" class="section">
	<div id="sequence-theme-collection" class="sequence">
			
		<div id="sequence-collection">
			
			<ul class="sequence-canvas">
				<li class="animate-in"><!--image 1-->
					<img class="collection-image" data-sequence-caption="Armstrong's Answer at UC Press Conference, 1979" src="images/armstrong-answer-moon-dust.jpg" alt="Armstrong's Answer on Moon Dust from the Press Conference held at UC for the 10th anniversary of the Apollo moon landing, 1979" />
						
				</li>
				
				<li><!--image 2-->				
					<img class="collection-image" data-sequence-caption="Armstrong's Lunar Map for &lsquo;21 December, 1968 Launch Date&rsquo;" src="images/armstrong-lunar-map.jpg" alt="Armstrong's Lunar Map for &lsquo;21 December, 1968 Launch Date&rsquo;" />		
				</li>
				
				<li><!--image 3-->
					<img class="collection-image" data-sequence-caption="&ldquo;My Vacation&rdquo;, A Children's Poem by Neil Armstrong" src="images/armstrong-childrens-poem.jpg" alt="&ldquo;My Vacation&rdquo;, A Children's Poem by Neil Armstrong" />
						
				</li>
				
				<li><!--image 4-->
					<img class="collection-image" data-sequence-caption="His Aviators Flight Log Book, USNR, 1949" src="images/armstrong-flight-log-book-cover.jpg" alt="His Aviators Flight Log Book, USNR, 1949" />
				</li>
				
				<li><!--image 5-->	
					<img class="collection-image" data-sequence-caption="A lecture presented by Neil Armstrong in Scotland, 1972" src="images/armstrong-communications-in-the-space-age.jpg" alt="&ldquo;Communications in the Space Age&rdquo; by Neil A. Armstrong, presented as a Mountbatten Lecture at the University of Edinburgh, Scotland, March 1972" />		
				</li>
					
				<li><!--image 6-->
					<img class="collection-image" data-sequence-caption="Photo of Neil Armstrong at UC" src="images/armstrong-photo.jpg" alt="Photo of Neil Armstrong at UC by Peggy Phalange, March 2, 1979. Courtesy of UC Magazine" />
				</li>
				
				<li><!--image 7-->
					<img class="collection-image" data-sequence-caption="HARP Apollo Diaphram Pump Presentation Abstract, 1975" src="images/armstrong-harp-abstract.jpg" alt="Presentation abstract created by the HARP group, presented at the American Association of Medical Instrumentation, Boston, Massachussets, March 20, 1975" />
				</li>
				
			</ul>
	
				<ul id="sequence-nav">
					<li class="sequence-nav-caption"></li>
					<span class="tooltip">Click on an image to browse through these digitized items in the Neil Armstrong Commemorative Archives Collection</span>
				</ul> 
	
				
				<span id="collection-link"><a href="http://drc.libraries.uc.edu/handle/2374.UC/713357" ><span class="tooltip link-icon">Click here to go directly to the Neil Armstrong Commemorative Archives</span></a></span>
				   
		</div><!--end sequence-collection-->
	</div><!--end sequence-theme-->
	
	        <div id="collection-header">
        
             	<h3 class="page-subtitle">The UC Neil Armstrong Commemorative Archives contains photographs and documents, including correspondence, relating to his time at UC. Also view his 1949 flight log book, a lunar map, and more&hellip;
              	</h3>
          
        	<h2><a class="link-icon" href="http://drc.libraries.uc.edu/handle/2374.UC/713357" >The Armstrong Collection</a></h2>
                
        </div><!--end collection-header-->
		
</div><!--end collection section-->