<!--<div id="armstrong-nav-menu-large-3d-objects">

    <div id="armstrong-menu" class="armstrong-nav">
        <ul class="clearfix">
			<li class="home"><a href="index.html">Home</a></li>

        </ul>

    </div>--><!--end armstrong-menu armstrong-nav clearfix-->

<!--</div>--><!--end armstrong-nav-menu-->

<div id="armstrong-nav-menu">

    <div id="armstrong-menu" class="armstrong-nav clearfix">
        <ul class="clearfix">
			<li><a href="http://uc.edu/armstrong#armstrong-home">Home</a></li>
            <li><a href="http://uc.edu/armstrong#armstrong-the-man">Armstrong, the Man</a></li>
            <li><a href="http://uc.edu/armstrong#time-at-uc">His Time at UC</a></li>
            <li><a href="http://uc.edu/armstrong#collection">The Collection</a></li>
        </ul>

        <a href="#" class="pull">Armstrong Menu</a>

    </div><!--end armstrong-menu armstrong-nav clearfix-->

</div><!--end armstrong-nav-menu-->
