<div id="armstrong-nav-menu">
          
    <div id="armstrong-menu" class="armstrong-nav clearfix">  
        <ul class="clearfix">  
			<li><a href="#armstrong-home">Home</a></li>
            <li><a href="#armstrong-the-man">Armstrong, the Man</a></li>  
            <li><a href="#time-at-uc">His Time at UC</a></li>  
            <li><a href="#collection">The Collection</a></li>     
        </ul>  
        
        <a href="#" class="pull">Armstrong Menu</a>  
        
    </div><!--end armstrong-menu armstrong-nav clearfix--> 
            
</div><!--end armstrong-nav-menu--> 