 <!--armstrong navigation menu-->
 <div class="home-nav-menu">
    <div id="armstrong-mobile-nav-menu">
        <div class="armstrong-nav-mobile-index">  
        <ul> 
            <li><a href="index.html">Home</a></li> 
            <li><a href="../armstrong-the-man.html">Armstrong, the Man</a></li>  
            <li><a href="../armstrong-time-at-uc.html">His Time at UC</a></li>  
            <li><a href="../armstrong-collection.html">The Collection</a></li>     
        </ul>  
 
		</div><!--end armstrong-menu armstrong-nav clearfix--> 
    </div><!--end armstrong-nav-menu--> 
</div>	   
    <!--end armstrong navigation menu-->