<a href="http://www.uc.edu/.html" id="uc-logo"><img src="../images/uc-logo.png" alt="UC Home" /></a>
    
<img src="../images/home-image.jpg" alt="In 1974, Neil Armstrong writes on a chalkboard in the UC College of Engineering. Photo Credit: Peggy Palange, UC Public Informaton Office" />

<div id="home-header" class="heading">
		<h1>
			Neil Armstrong
		</h1> 
		<h2 class="home-subtitle">
			Engineer. Pilot. Astronaut. Teacher.
		</h2>           
</div><!--end home-header-->