
	<!--armstrong footer-->
	<div id="armstrong-footer" class="armstrong-nav clearfix section">
			
		
			<ul class="clearfix">
					<li><a href="../armstrong-learn-more.html">Learn More about Neil Armstrong</a></li>
					<li><a href="../armstrong-about-the-website.html">About the UC Commemorative Website</a></li>
					<li><a href="../armstrong-on-uc-campus.html">On UC Campus</a></li>
					<li><a class="tall" href="http://drc.libraries.uc.edu/handle/2374.UC/713357" >The UC Commemorative Archives Collection</a></li>					
			</ul>				
					
	</div><!--end armstrong-footer nav clearfix-->
	<!--end armstrong footer-->
	