
	<!--uc footer-->
	<div id="uc-footer" class="uc-header-footer">
		<p>
			<span id="info">
				<a href="http://www.uc.edu/contact.html" >Contact Us</a> | University of Cincinnati <br />
		
				2600 Clifton Ave., Cincinnati OH 45221 | 
				<a href="http://admissions.uc.edu/.html" >Undergraduate Admissions</a>: 513-556-1100 |  
				<a href="http://grad.uc.edu/" >Graduate Admission</a>: 513-556-4335 | 
				<a href="https://www.jobsatuc.com/" >Jobs at UC</a>
			</span>
			<span id="copyright">
				<a href="http://www.ipo.uc.edu/index.cfm?fuseaction=home.infringement">Copyright Information</a> &copy; 2015
			</span>
		</p>
	</div>
	<!--end uc footer-->
	
	<!--google translate button-->
	<div id="google_translate_element"></div><script type="text/javascript">
function googleTranslateElementInit() {
  new google.translate.TranslateElement({pageLanguage: 'en', layout: google.translate.TranslateElement.FloatPosition.BOTTOM_LEFT}, 'google_translate_element');
}
</script><script type="text/javascript" src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>
        

	<!--end google translate button-->

<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try {
var pageTracker = _gat._getTracker("UA-8099459-5");
pageTracker._trackPageview();
} catch(err) {}</script>