 <!--armstrong navigation menu-->
    <div id="armstrong-nav-menu">
        <div id="armstrong-menu" class="armstrong-nav clearfix">  
        <ul class="clearfix"> 
            <li><a href="mobile/index.html">Home</a></li> 
            <li><a href="armstrong-the-man.html">Armstrong, the Man</a></li>  
            <li><a href="armstrong-time-at-uc.html">His Time at UC</a></li>  
            <li><a href="armstrong-collection.html">The Collection</a></li>     
        </ul>   
		
		<a href="#" class="pull">Armstrong Menu</a>
		</div><!--end armstrong-menu armstrong-nav clearfix--> 
    </div><!--end armstrong-nav-menu-->    
    <!--end armstrong navigation menu-->